features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://Rust-Logo_0.jpg'
favicon:
  use_default: true
